---
title: "R Lab 1 | Assignment"
author: "Jeremy Morris"
affiliation-title: "University of Utah"
date: last-modified
title-block-style: default
title-block-banner: true
format: 
  html:
      embed-resources: true
      theme: flatly
      code-block-bg: true
      code-block-border-left: "#31BAE9"
      highlight-style: printing
execute:
    message: false
    warning: false
    error: false
---

```{r setup}
#| echo: false
library(tidyverse)
theme_local <- function(bs=15,...){
    theme_bw(base_size=bs) +
    theme(
        legend.position='bottom',
        panel.grid=element_blank(),
        axis.line.x=element_line(color='black'),
        axis.line.y=element_line(color='black'),
        panel.border=element_blank(),
        ...
    )
}
```

## Task 1

*Answer the following question below: What is one thing you have learned this semester?*

## Task 2

*Interpret the following chart (put your answer below the visualization).*

```{r chart-data}
#| echo: false
wb <- read_csv('world-bank.csv')
comp_vars <- c('GDP per capita (constant 2015 US$)','Government expenditure on education, total (% of GDP)')
wb_comp <- wb |>
    mutate(`2017 [YR2017]`=as.numeric(`2017 [YR2017]`)) |>
    filter(!is.na(`Country Name`)) |>
    pivot_wider(names_from=`Series Code`,values_from=`2017 [YR2017]`,id_cols=c(`Country Name`,`Country Code`)) |>
    mutate(cc=case_when(
        SE.XPD.TOTL.GB.ZS < 7 ~ 'low',
        SE.XPD.TOTL.GB.ZS > 24 ~ 'high',
        `Country Code` == 'USA' ~ 'USA',
        TRUE ~ 'other'
    ))
```

```{r chart1}
#| fig.align: center
#| fig.width: 10
#| fig.height: 6
#| echo: false
ggplot(wb_comp,aes(y=`SE.XPD.TOTL.GB.ZS`,x=`NY.GDP.MKTP.KD`/1000000)) +
    geom_point(aes(color=cc),data=filter(wb_comp,cc == 'other')) +
    geom_point(aes(color=cc),size=2,data=filter(wb_comp,cc != 'other')) +
    ggrepel::geom_text_repel(aes(label=`Country Name`),size=5,data=filter(wb_comp,cc != 'other')) +
    scale_x_log10(labels=scales::dollar) +
    scale_color_manual(values=c('#185B77','#84CAE7','#D9D6D3','#22333B')) +
    labs(y='Govt expenditure on education,\ntotal (% of govt expenditure)',x='GDP (constant 2015 US$)\nMillions') +
    theme_local() + theme(legend.position='none')
```